### ISSUE TITLE
clasp@2.0

### ISSUE THREAD

**Issue by grant** [google/clasp#70]
For the next version of `clasp`, I'd like to make it ridiculously simple and easy to use the tool.
Let's use features of modern CLIs.

## Features
- [ ] `clasp`/`clasp push --watch` (watches project file changes, pushes and logs updates)
- [x] `clasp list` #93 (requires Drive Scope)
- [ ] `clasp run foo` #11 (define deployment name?)
- [ ] `clasp clone <scriptID>` (autocomplete #69)
- [x] `clasp logs` #46 
- [ ] Optional Typescript Support #77 ([Types](https://www.typescriptlang.org/docs/home.html) / [No Types](https://www.youtube.com/watch?v=wzMrK-aGCug))
  - [ ] Create a conversion guide ([ex](https://github.com/Microsoft/TypeScript-React-Conversion-Guide#typescript-react-conversion-guide))
- [ ] Autocomplete (vorpal) ([example](https://twitter.com/sindresorhus/status/974343649600323584))
  - tab complete
  - select options

These updates will require a major version update (v2).

## Docs
- [ ] Update docs with all options for all commands
- [ ] Add examples of ignoring files
  - `clasp status`?
- [ ] Add a better way to version npm/git versions

## Social
- Blog ([ex](https://medium.com/@cretezy/noderize-create-node-apps-in-30-seconds-2ac1a79baeff))
- Video
- Tweet

**Comment by JeanRemiDelteil** [comment]
Hi @grant, on this note (the "easy" part), I've update my [Chrome extension for AppsScript web Editor](https://chrome.google.com/webstore/detail/ciggahcpieccaejjdpkllokejakhkome).

It now displays the files in the left Sidebar with a Folder view if you named them with '/'.
For example: folder/subFolder/file

This way, when working with a project pushed with CLASP, the web editor will also display the folders !

![gas-folder](https://user-images.githubusercontent.com/9743907/37745826-629eef9e-2d77-11e8-8f83-55ce49ada3bb.png)

**Comment by grant** [comment]
@JeanRemiDelteil This is an awesome extension! Didn't know about it.
LMK other features you want to see in `clasp` or Apps Script in general.

**Comment by JeanRemiDelteil** [comment]
thanks ! I forgot to mention that it's available on Github here: [https://github.com/JeanRemiDelteil/appsScriptColor](https://github.com/JeanRemiDelteil/appsScriptColor)

**Comment by diminishedprime** [comment]
If options can be presented in 2.0, it be great if `clasp redeploy` prompted the user to choose from the available deployments and versions.

**Comment by grant** [comment]
@JeanRemiDelteil I'll try to cut a release this week.

**Comment by grant** [comment]
The release will be next week actually.

**Comment by grant** [comment]
Delayed the latest release by a month.
I'll close this mega issue in favor of smaller issues as the state of things here is hard to maintain.

**Comment by imthenachoman** [comment]
@JeanRemiDelteil Love love love the extension. How can we support your work?
